resolver: 'lts-16.9'
save-hackage-creds: false

packages:
- '.'

flags:
  patat:
    patat-make-man: true

extra-deps:
- 'goldplate-0.1.2'
- 'pandoc-2.11.2'
- 'pandoc-types-1.22'
- 'skylighting-0.10.1'
