resolver: 'lts-21.0'
compiler: 'ghc-9.4.3'
save-hackage-creds: false

packages:
- '.'

flags:
  patat:
    patat-make-man: true

extra-deps:
- 'pandoc-3.1.2'

nix:
  packages:
  - 'pkgconfig'
  - 'zlib'
